---
abstract: 'Fast Common Gateway Interface Class for CGI::Pure.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.01
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Pure-Fast
no_index:
  directory:
    - inc
    - t
requires:
  CGI::Pure: 0.01
  FCGI: 0
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CGI-Pure-Fast
  homepage: https://github.com/tupinek/CGI-Pure-Fast
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/CGI-Pure-Fast
version: 0.02
